// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/sandstone2/fiberpoc/common/services (interfaces: FooServiceInterface)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_foo_service.go -package=mocks -mock_names=FooServiceInterface=MockFooService gitlab.com/sandstone2/fiberpoc/common/services FooServiceInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "gitlab.com/sandstone2/fiberpoc/common/models"
	gomock "go.uber.org/mock/gomock"
)

// MockFooService is a mock of FooServiceInterface interface.
type MockFooService struct {
	ctrl     *gomock.Controller
	recorder *MockFooServiceMockRecorder
	isgomock struct{}
}

// MockFooServiceMockRecorder is the mock recorder for MockFooService.
type MockFooServiceMockRecorder struct {
	mock *MockFooService
}

// NewMockFooService creates a new mock instance.
func NewMockFooService(ctrl *gomock.Controller) *MockFooService {
	mock := &MockFooService{ctrl: ctrl}
	mock.recorder = &MockFooServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFooService) EXPECT() *MockFooServiceMockRecorder {
	return m.recorder
}

// CreateFoo mocks base method.
func (m *MockFooService) CreateFoo(name string) (*models.Foo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFoo", name)
	ret0, _ := ret[0].(*models.Foo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFoo indicates an expected call of CreateFoo.
func (mr *MockFooServiceMockRecorder) CreateFoo(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFoo", reflect.TypeOf((*MockFooService)(nil).CreateFoo), name)
}

// DeleteFoos mocks base method.
func (m *MockFooService) DeleteFoos() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFoos")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFoos indicates an expected call of DeleteFoos.
func (mr *MockFooServiceMockRecorder) DeleteFoos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFoos", reflect.TypeOf((*MockFooService)(nil).DeleteFoos))
}

// GetFoos mocks base method.
func (m *MockFooService) GetFoos() (*[]models.Foo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFoos")
	ret0, _ := ret[0].(*[]models.Foo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFoos indicates an expected call of GetFoos.
func (mr *MockFooServiceMockRecorder) GetFoos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFoos", reflect.TypeOf((*MockFooService)(nil).GetFoos))
}

// UpdateFoo mocks base method.
func (m *MockFooService) UpdateFoo(fooId int64, name string) (*models.Foo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFoo", fooId, name)
	ret0, _ := ret[0].(*models.Foo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFoo indicates an expected call of UpdateFoo.
func (mr *MockFooServiceMockRecorder) UpdateFoo(fooId, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFoo", reflect.TypeOf((*MockFooService)(nil).UpdateFoo), fooId, name)
}
