// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/sandstone2/fiberpoc/common/repos (interfaces: FooRepoInterface)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_foo_repo.go -package=mocks -mock_names=FooRepoInterface=MockFooRepo gitlab.com/sandstone2/fiberpoc/common/repos FooRepoInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "gitlab.com/sandstone2/fiberpoc/common/models"
	gomock "go.uber.org/mock/gomock"
)

// MockFooRepo is a mock of FooRepoInterface interface.
type MockFooRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFooRepoMockRecorder
	isgomock struct{}
}

// MockFooRepoMockRecorder is the mock recorder for MockFooRepo.
type MockFooRepoMockRecorder struct {
	mock *MockFooRepo
}

// NewMockFooRepo creates a new mock instance.
func NewMockFooRepo(ctrl *gomock.Controller) *MockFooRepo {
	mock := &MockFooRepo{ctrl: ctrl}
	mock.recorder = &MockFooRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFooRepo) EXPECT() *MockFooRepoMockRecorder {
	return m.recorder
}

// CreateFoo mocks base method.
func (m *MockFooRepo) CreateFoo(name string) (*models.Foo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFoo", name)
	ret0, _ := ret[0].(*models.Foo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFoo indicates an expected call of CreateFoo.
func (mr *MockFooRepoMockRecorder) CreateFoo(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFoo", reflect.TypeOf((*MockFooRepo)(nil).CreateFoo), name)
}

// DeleteFoos mocks base method.
func (m *MockFooRepo) DeleteFoos() (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFoos")
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteFoos indicates an expected call of DeleteFoos.
func (mr *MockFooRepoMockRecorder) DeleteFoos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFoos", reflect.TypeOf((*MockFooRepo)(nil).DeleteFoos))
}

// GetFoos mocks base method.
func (m *MockFooRepo) GetFoos() (*[]models.Foo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFoos")
	ret0, _ := ret[0].(*[]models.Foo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFoos indicates an expected call of GetFoos.
func (mr *MockFooRepoMockRecorder) GetFoos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFoos", reflect.TypeOf((*MockFooRepo)(nil).GetFoos))
}

// UpdateFoo mocks base method.
func (m *MockFooRepo) UpdateFoo(fooId int64, name string) (*models.Foo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateFoo", fooId, name)
	ret0, _ := ret[0].(*models.Foo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateFoo indicates an expected call of UpdateFoo.
func (mr *MockFooRepoMockRecorder) UpdateFoo(fooId, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateFoo", reflect.TypeOf((*MockFooRepo)(nil).UpdateFoo), fooId, name)
}
