// Code generated by MockGen. DO NOT EDIT.
// Source: gitlab.com/sandstone2/fiberpoc/common/interfaces (interfaces: PgxRowsInterface)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_pgx_rows.go -package=mocks -mock_names=PgxRowsInterface=MockPgxRows gitlab.com/sandstone2/fiberpoc/common/interfaces PgxRowsInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPgxRows is a mock of PgxRowsInterface interface.
type MockPgxRows struct {
	ctrl     *gomock.Controller
	recorder *MockPgxRowsMockRecorder
	isgomock struct{}
}

// MockPgxRowsMockRecorder is the mock recorder for MockPgxRows.
type MockPgxRowsMockRecorder struct {
	mock *MockPgxRows
}

// NewMockPgxRows creates a new mock instance.
func NewMockPgxRows(ctrl *gomock.Controller) *MockPgxRows {
	mock := &MockPgxRows{ctrl: ctrl}
	mock.recorder = &MockPgxRowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPgxRows) EXPECT() *MockPgxRowsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPgxRows) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockPgxRowsMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPgxRows)(nil).Close))
}

// Err mocks base method.
func (m *MockPgxRows) Err() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Err")
	ret0, _ := ret[0].(error)
	return ret0
}

// Err indicates an expected call of Err.
func (mr *MockPgxRowsMockRecorder) Err() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Err", reflect.TypeOf((*MockPgxRows)(nil).Err))
}

// Next mocks base method.
func (m *MockPgxRows) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockPgxRowsMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockPgxRows)(nil).Next))
}

// Scan mocks base method.
func (m *MockPgxRows) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockPgxRowsMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockPgxRows)(nil).Scan), dest...)
}
